"""Initial migration with all models

Revision ID: 338cc9f9ac27
Revises: 
Create Date: 2025-11-18 21:23:35.683521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338cc9f9ac27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('bug_description', sa.Text(), nullable=False),
    sa.Column('test_command', sa.String(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_cases_name'), 'evaluation_cases', ['name'], unique=True)
    op.create_table('evaluation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evaluation_case_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_created_at'), 'evaluation_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_results_evaluation_case_id'), 'evaluation_results', ['evaluation_case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_task_id'), 'evaluation_results', ['task_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_task_id'), 'feedback', ['task_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_task_id'), 'llm_usage', ['task_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_timestamp'), 'llm_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_created_at'), 'prompt_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_index(op.f('ix_prompt_versions_version'), 'prompt_versions', ['version'], unique=False)
    op.create_table('task_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_metrics_task_id'), 'task_metrics', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_metrics_timestamp'), 'task_metrics', ['timestamp'], unique=False)
    op.add_column('tasks', sa.Column('test_output_before', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('e2e_test_path', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('job_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_job_id'), 'tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_job_id'), table_name='tasks')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'job_id')
    op.drop_column('tasks', 'e2e_test_path')
    op.drop_column('tasks', 'test_output_before')
    op.drop_index(op.f('ix_task_metrics_timestamp'), table_name='task_metrics')
    op.drop_index(op.f('ix_task_metrics_task_id'), table_name='task_metrics')
    op.drop_table('task_metrics')
    op.drop_index(op.f('ix_prompt_versions_version'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_created_at'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_llm_usage_user_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_timestamp'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_task_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_task_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_evaluation_results_task_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_evaluation_case_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_created_at'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_evaluation_cases_name'), table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    # ### end Alembic commands ###
